server:
  port: 7002

eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka7002.com
  client:
    # false表示不向Eureka Server注册自己
    register-with-eureka: false
    # false表示是否从Eureka Server获取注册信息
    fetch-registry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址间可使用,分隔
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/