server:
  port: 8080

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    # f表示向Eureka Server注册
    register-with-eureka: false
    # 表示从Eureka Server获取注册信息 集群时必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: false
    # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址，多个地址间可使用,分隔
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/

# 设置feign客户端超时时间，默认超时时间为1s（openfeign默认支持ribbon）
ribbon:
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ReadTimeout: 5000
  # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ConnectTimeout: 5000

logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.atguigu.springcloud.service.PaymentFeignService: debug